# Generated by Django 5.1.2 on 2024-11-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('CMPN', 'Computer Engineering'), ('EXTC', 'Electronics & Telecommunication'), ('IT', 'Information Technology'), ('MECH', 'Mechanical Engineering'), ('ELEC', 'Electrical Engineering')], max_length=4),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('CMPN', 'Computer Engineering'), ('EXTC', 'Electronics & Telecommunication'), ('IT', 'Information Technology'), ('MECH', 'Mechanical Engineering'), ('ELEC', 'Electrical Engineering')], max_length=4),
        ),
    ]
